#! /usr/bin/env python3

somearray = [1, 2, 3, 4, 5]
print(somearray)

rotations = 2

def left_rotations(somearray):

    new_list = []
    new_list.append(somearray.pop())


left_rotations(somearray)
